[workspace]
members = [
	"subr",
]

[workspace.package]
version = "0.11.0"
edition = "2021"

[workspace.dependencies]
pyo3 = { version = ">=0.19", features = ["extension-module"] }
subversion = { verrsion = ">=0.0.4", features = ["pyo3"] }
pyo3-filelike = { version = "0.2" }
