[workspace]
resolver = "1"
members = [
	"subr",
	"ra", "common",
]

[workspace.package]
version = "0.11.0"
edition = "2021"

[workspace.dependencies]
pyo3 = { version = ">=0.22", features = ["extension-module"] }
subversion = { version = ">=0.0.6", features = ["pyo3"] }
#subversion = { path = "../subversion-rs", features = ["pyo3"] }
#subversion = { git = "https://github.com/jelmer/subversion-rs", features = ["pyo3"] }
#subversion = { path = "../subversion-rs", features = ["pyo3"] }
pyo3-filelike = { version = "0.3" }
