tag-name = "subvertpy-$VERSION"
verify-command = "make check"
release-timeout = 5

[[update_version]]
path = "subvertpy/__init__.py"
match = "^__version__ = (.*)$"
new-line = "__version__ = $TUPLED_VERSION"
