from typing import IO

from subvertpy._typing import PackNotifyFunc

LOAD_UUID_DEFAULT: int
LOAD_UUID_IGNORE: int
LOAD_UUID_FORCE: int

CHECKSUM_MD5: int
CHECKSUM_SHA1: int

PATH_CHANGE_MODIFY: int
PATH_CHANGE_ADD: int
PATH_CHANGE_DELETE: int
PATH_CHANGE_REPLACE: int

# Description of a single path change entry as returned by
# FileSystemRoot.paths_changed. Fields correspond to
# svn_fs_path_change2_t (change_kind, text_mod, prop_mod, node_kind,
# copyfrom_rev, copyfrom_path).
PathChange = dict[str, object]

class Stream:
    def read(self, size: int | None = ...) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def close(self) -> None: ...

class FileSystemRoot:
    def paths_changed(self) -> dict[str, PathChange]: ...
    def is_dir(self, path: str) -> bool: ...
    def is_file(self, path: str) -> bool: ...
    def file_length(self, path: str) -> int: ...
    def proplist(self, path: str) -> dict[str, bytes]: ...
    def node_proplist(self, path: str) -> dict[str, bytes]: ...

class FileSystem:
    def get_uuid(self) -> str: ...
    def get_youngest_revision(self) -> int: ...
    def youngest_revision(self) -> int: ...
    def get_revision_root(self, revnum: int) -> FileSystemRoot: ...
    def revision_root(self, revnum: int) -> FileSystemRoot: ...
    def get_revision_proplist(self, revnum: int) -> dict[str, bytes]: ...
    def revision_proplist(self, revnum: int) -> dict[str, bytes]: ...

class Repository:
    def __init__(self, path: str) -> None: ...
    def fs(self) -> FileSystem: ...
    def has_capability(self, capability: str) -> bool: ...
    def verify(
        self,
        feedback_stream: IO[bytes] | None = ...,
        start_rev: int | None = ...,
        end_rev: int | None = ...,
    ) -> None: ...
    def pack(self, notify_func: PackNotifyFunc | None = ...) -> None: ...
    def hotcopy(
        self,
        dest_path: str,
        clean_logs: bool = ...,
        incremental: bool = ...,
    ) -> None: ...
    def load_fs(
        self,
        data_stream: IO[bytes],
        feedback_stream: IO[bytes] | None = ...,
        use_pre_commit_hook: bool = ...,
        use_post_commit_hook: bool = ...,
        uuid_action: int = ...,
    ) -> None: ...

# Repository config / fs config are unused placeholders in the current
# Rust binding; typed as opaque.
def create(
    path: str,
    config: object | None = ...,
    fs_config: object | None = ...,
) -> Repository: ...
def delete(path: str) -> None: ...
def hotcopy(
    src_path: str,
    dest_path: str,
    clean_logs: bool = ...,
    incremental: bool = ...,
) -> None: ...
def version() -> tuple[int, int, int, str]: ...
def api_version() -> tuple[int, int, int, str]: ...
