name: debian-unstable-build
on: [push, pull_request]
jobs:
  build:
    name: subvertpy build on Debian unstable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subvertpy code
        uses: actions/checkout@v6
      - name: Build subvertpy on Debian unstable
        uses: vjik/docker-run@v1
        with:
          image: debian:unstable
          volumes: ${{ github.workspace }}:/subvertpy:rw
          workdir: /subvertpy
          command: |
            apt update -y
            apt install -y python3 libpython3-dev python3-venv \
              build-essential libsvn-dev cargo pkg-config libclang-dev \
              libutf8proc-dev libsqlite3-dev liblz4-dev libxxhash-dev subversion

            # Work around https://bugs.debian.org/1055242
            svnversion=$(svn --version | grep -oP 'svn, version \K\d+\.\d+\.\d+')
            sed -i "s/^Version: *$/Version: $svnversion/" /usr/lib/*/pkgconfig/libsvn_*.pc

            export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig

            python3 -m venv ~/venv
            . ~/venv/bin/activate

            pip install setuptools-rust
            pip install .
