name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        svn-version: [1.13.0, 1.12.2, 1.11.1, 1.10.6, 1.9.7, 1.8.19, 1.7.19, 1.6.21, 1.5.9]

    steps:
    - name: Install dependencies (apt)
      run: sudo apt install libapr1-dev libaprutil1-dev libdb5.3-dev liblz4-dev libsasl2-dev libperl-dev libserf-dev libsqlite3-dev libtool python-all-dev libneon27-gnutls-dev libutf8proc-dev
      if: "matrix.os == 'ubuntu-latest'"
    - name: Install Subversion
      run: |
        wget https://archive.apache.org/dist/subversion/subversion-${{ matrix.svn-version }}.tar.gz
        tar xvfz subversion-${{ matrix.svn-version }}.tar.gz
        cd subversion-${{ matrix.svn-version }}
        ./configure
        make
        sudo make install
        sudo ldconfig -v
        cd ..
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip coverage codecov flake8 fastimport
    - name: Style checks
      run: |
        python -m flake8
    - name: Build
      run: |
        python setup.py build_ext -i
    - name: Coverage test suite run
      run: |
        python -m coverage run -p -m unittest subvertpy.tests.test_suite
