name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
#        os: [ubuntu-latest]
#        svn-version: [1.13.0, 1.12.2, 1.11.1, 1.10.6, 1.9.7, 1.8.19, 1.7.19, 1.6.21, 1.5.9]
        include:
#          - os: macos-latest
#            python-version: 2.7
#          - os: macos-latest
#            python-version: 3.5
#          - os: macos-latest
#            python-version: 3.6
#          - os: macos-latest
#            python-version: 3.7
#          - os: macos-latest
#            python-version: 3.8
          - os: windows-latest
            python-version: 3.8
            svn-version: 1.13.0

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (apt)
      run: sudo apt install libapr1-dev libaprutil1-dev libdb5.3-dev liblz4-dev libsasl2-dev libperl-dev libserf-dev libsqlite3-dev libtool python-all-dev libneon27-gnutls-dev libutf8proc-dev
      if: "matrix.os == 'ubuntu-latest'"
    - name: Install dependencies (brew)
      run: |
        brew install subversion apr-util apr
        echo "::add-path::$(brew --prefix)/opt/subversion/libexec"
        echo "::add-path::$(brew --prefix)/opt/apr-util/bin"
        echo "::add-path::$(brew --prefix)/opt/apr/bin"
      if: "matrix.os == 'macos-latest'"
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2020.01
        ./bootstrap-vcpkg.sh
      shell: bash
      if: "matrix.os == 'windows-latest'"
    - name: Install dependencies (Windows)
      run: |
        ./vcpkg/vcpkg.exe install apr:x64-windows apr-util:x64-windows sqlite3:x64-windows zlib:x64-windows utf8proc:x64-windows openssl:x64-windows berkeleydb:x64-windows lz4:x64-windows python2:x64-windows
        curl https://downloads.apache.org/serf/serf-1.3.9.zip -o serf.zip
        unzip -q serf.zip
        cd serf-1.3.9
        curl -L http://prdownloads.sourceforge.net/scons/scons-local-2.3.0.zip -o scons-local.zip
        unzip -q scons-local.zip
        python2 ./scons.py
        python2 ./scons.py install
      if: "matrix.os == 'windows-latest'"
    - name: Download Subversion (Windows/Linux)
      run: |
        curl https://archive.apache.org/dist/subversion/subversion-${{ matrix.svn-version }}.tar.gz -o subversion.tar.gz
        tar xfz subversion.tar.gz
        cd subversion-${{ matrix.svn-version }}
      if: "matrix.os == 'windows-latest' || matrix.os == 'ubuntu-latest'"
    - name: Install Subversion (Windows)
      run: |
        cd subversion-${{ matrix.svn-version }}
        python gen-make.py
        msbuild subversion_vcnet.sln /t:__MORE__ /p:Configuration=Release
      if: "matrix.os == 'windows-latest'"
    - name: Install Subversion (Linux)
      run: |
        ./configure
        make
        sudo make install
        sudo ldconfig -v
        cd ..
      if: "matrix.os == 'ubuntu-latest'"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip coverage codecov flake8 fastimport
    - name: Style checks
      run: |
        python -m flake8
    - name: Build (Linux)
      run: |
        python setup.py build_ext -i
      if: "matrix.os == 'ubuntu-latest'"
    - name: Build (Mac OS X)
      run: |
        python setup.py build_ext -i
      if: "matrix.os == 'macos-latest'"
    - name: Coverage test suite run
      run: |
        python -m coverage run -p -m unittest subvertpy.tests.test_suite
