name: sdist
on: [push, pull_request]
jobs:
  sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subvertpy code
        uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
          sudo apt-get install -y libsvn-dev libutf8proc-dev libclang-dev subversion
          # Work around https://bugs.debian.org/1055242
          svnversion=$(svn --version | grep -oP 'svn, version \K\d+\.\d+\.\d+')
          sudo sed -i "s/^Version: $/Version: $svnversion/" /usr/lib/*/pkgconfig/libsvn_*.pc
      - name: Build sdist
        run: |
          pip install build setuptools-rust
          python -m build --sdist --outdir dist/
      - name: Install sdist and test import
        run: |
          pip install dist/*.tar.gz
          cd /tmp && python -c "from subvertpy import client, ra, repos, subr, wc"
      - uses: actions/upload-artifact@v4
        with:
          name: subvertpy-sdist
          path: dist/*.tar.gz
