name: windows-wheels
on: [push, pull_request]
jobs:
  windows:
    name: subvertpy Python ${{ matrix.python-version }} wheel build on windows
    runs-on: windows-latest
    env:
      VCPKG_INSTALL_DIR: ${{ github.workspace }}\vcpkg\installed\x64-windows-release
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout subvertpy code
        uses: actions/checkout@v6
      - name: Install MSYS2 shell
        uses: msys2/setup-msys2@v2
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        id: python-install
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build, cibuildwheel and pytest Python packages
        run: |
          set PATH=%Python3_ROOT_DIR%\Scripts;%PATH%
          pip install build cibuildwheel pytest
      - name: Install build dependencies with vcpkg
        uses: johnwason/vcpkg-action@v8
        id: vcpkg
        continue-on-error: true
        with:
          pkgs: subversion
          triplet: x64-windows-release
          extra-args: --allow-unsupported --recurse --keep-going
          token: ${{ github.token }}
      - name: Sets CIBW_BUILD environment variable
        env:
          pyVer: "${{matrix.python-version}}"
        run: |
          echo "CIBW_BUILD=cp${pyVer/./}-win_amd64" >> $GITHUB_ENV
        shell: msys2 {0}
      - name: Build subvertpy wheel with cibuildwheel
        env:
            LIB: ${{ env.VCPKG_INSTALL_DIR }}/lib
            SYSTEM_DEPS_APR_1_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_APR_1_LIB: libapr-1
            SYSTEM_DEPS_APR_1_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_APR_1_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include
            SYSTEM_DEPS_APR_UTIL_1_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_APR_UTIL_1_LIB: libaprutil-1
            SYSTEM_DEPS_APR_UTIL_1_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_APR_UTIL_1_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include
            SYSTEM_DEPS_LIBSVN_CLIENT_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_LIBSVN_CLIENT_LIB: libsvn_client-1
            SYSTEM_DEPS_LIBSVN_CLIENT_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_LIBSVN_CLIENT_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include\subversion-1;${{ env.VCPKG_INSTALL_DIR }}\include
            SYSTEM_DEPS_LIBSVN_DELTA_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_LIBSVN_DELTA_LIB: libsvn_delta-1
            SYSTEM_DEPS_LIBSVN_DELTA_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_LIBSVN_DELTA_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include\subversion-1;${{ env.VCPKG_INSTALL_DIR }}\include
            SYSTEM_DEPS_LIBSVN_DIFF_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_LIBSVN_DIFF_LIB: libsvn_diff-1
            SYSTEM_DEPS_LIBSVN_DIFF_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_LIBSVN_DIFF_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include\subversion-1;${{ env.VCPKG_INSTALL_DIR }}\include
            SYSTEM_DEPS_LIBSVN_FS_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_LIBSVN_FS_LIB: libsvn_fs-1
            SYSTEM_DEPS_LIBSVN_FS_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_LIBSVN_FS_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include\subversion-1;${{ env.VCPKG_INSTALL_DIR }}\include
            SYSTEM_DEPS_LIBSVN_RA_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_LIBSVN_RA_LIB: libsvn_ra-1
            SYSTEM_DEPS_LIBSVN_RA_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_LIBSVN_RA_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include\subversion-1;${{ env.VCPKG_INSTALL_DIR }}\include
            SYSTEM_DEPS_LIBSVN_REPOS_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_LIBSVN_REPOS_LIB: libsvn_repos-1
            SYSTEM_DEPS_LIBSVN_REPOS_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_LIBSVN_REPOS_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include\subversion-1;${{ env.VCPKG_INSTALL_DIR }}\include
            SYSTEM_DEPS_LIBSVN_SUBR_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_LIBSVN_SUBR_LIB: libsvn_subr-1
            SYSTEM_DEPS_LIBSVN_SUBR_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_LIBSVN_SUBR_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include\subversion-1;${{ env.VCPKG_INSTALL_DIR }}\include
            SYSTEM_DEPS_LIBSVN_WC_NO_PKG_CONFIG: "1"
            SYSTEM_DEPS_LIBSVN_WC_LIB: libsvn_wc-1
            SYSTEM_DEPS_LIBSVN_WC_SEARCH_NATIVE: ${{ env.VCPKG_INSTALL_DIR }}\lib
            SYSTEM_DEPS_LIBSVN_WC_INCLUDE: ${{ env.VCPKG_INSTALL_DIR }}\include\subversion-1;${{ env.VCPKG_INSTALL_DIR }}\include
            CIBW_BUILD_VERBOSITY: 1
            CIBW_ENVIRONMENT_PASS_WINDOWS: >-
              LIB
              SYSTEM_DEPS_APR_1_NO_PKG_CONFIG SYSTEM_DEPS_APR_1_LIB SYSTEM_DEPS_APR_1_SEARCH_NATIVE SYSTEM_DEPS_APR_1_INCLUDE
              SYSTEM_DEPS_APR_UTIL_1_NO_PKG_CONFIG SYSTEM_DEPS_APR_UTIL_1_LIB SYSTEM_DEPS_APR_UTIL_1_SEARCH_NATIVE SYSTEM_DEPS_APR_UTIL_1_INCLUDE
              SYSTEM_DEPS_LIBSVN_CLIENT_NO_PKG_CONFIG SYSTEM_DEPS_LIBSVN_CLIENT_LIB SYSTEM_DEPS_LIBSVN_CLIENT_SEARCH_NATIVE SYSTEM_DEPS_LIBSVN_CLIENT_INCLUDE
              SYSTEM_DEPS_LIBSVN_DELTA_NO_PKG_CONFIG SYSTEM_DEPS_LIBSVN_DELTA_LIB SYSTEM_DEPS_LIBSVN_DELTA_SEARCH_NATIVE SYSTEM_DEPS_LIBSVN_DELTA_INCLUDE
              SYSTEM_DEPS_LIBSVN_DIFF_NO_PKG_CONFIG SYSTEM_DEPS_LIBSVN_DIFF_LIB SYSTEM_DEPS_LIBSVN_DIFF_SEARCH_NATIVE SYSTEM_DEPS_LIBSVN_DIFF_INCLUDE
              SYSTEM_DEPS_LIBSVN_FS_NO_PKG_CONFIG SYSTEM_DEPS_LIBSVN_FS_LIB SYSTEM_DEPS_LIBSVN_FS_SEARCH_NATIVE SYSTEM_DEPS_LIBSVN_FS_INCLUDE
              SYSTEM_DEPS_LIBSVN_RA_NO_PKG_CONFIG SYSTEM_DEPS_LIBSVN_RA_LIB SYSTEM_DEPS_LIBSVN_RA_SEARCH_NATIVE SYSTEM_DEPS_LIBSVN_RA_INCLUDE
              SYSTEM_DEPS_LIBSVN_REPOS_NO_PKG_CONFIG SYSTEM_DEPS_LIBSVN_REPOS_LIB SYSTEM_DEPS_LIBSVN_REPOS_SEARCH_NATIVE SYSTEM_DEPS_LIBSVN_REPOS_INCLUDE
              SYSTEM_DEPS_LIBSVN_SUBR_NO_PKG_CONFIG SYSTEM_DEPS_LIBSVN_SUBR_LIB SYSTEM_DEPS_LIBSVN_SUBR_SEARCH_NATIVE SYSTEM_DEPS_LIBSVN_SUBR_INCLUDE
              SYSTEM_DEPS_LIBSVN_WC_NO_PKG_CONFIG SYSTEM_DEPS_LIBSVN_WC_LIB SYSTEM_DEPS_LIBSVN_WC_SEARCH_NATIVE SYSTEM_DEPS_LIBSVN_WC_INCLUDE
            CIBW_BEFORE_BUILD_WINDOWS: pip install delvewheel
            CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >
                delvewheel repair -v -w {dest_dir} --analyze-existing
                --add-path ${{ env.VCPKG_INSTALL_DIR }}\bin
                {wheel}
        run: python -m cibuildwheel --output-dir wheelhouse
      - name: Cleanup subvertpy repo to run tests with installed wheel
        run: rm -rf subvertpy
        shell: msys2 {0}
      - name: Test built wheel can be installed and imported
        working-directory: wheelhouse
        run: |
          python_dir=$(cygpath -u $Python3_ROOT_DIR)
          export PATH=$python_dir:$python_dir/Scripts:$PATH

          pip install $(ls -t | head -1)

          # check modules import and https support
          python -c "
          from subvertpy import client, ra, repos, subr, wc;
          client = client.Client(auth=ra.Auth([ra.get_username_provider()]));
          client.info('https://svn.pld-linux.org/svn')"

          pip install pytest
          cd ../ && rm -rf subvertpy && python -m pytest tests
        shell: msys2 {0}
      - uses: actions/upload-artifact@v4
        with:
          name: subvertpy-wheel-windows-${{ matrix.python-version }}
          path: ./wheelhouse/*.whl
